language: python
python:
- "2.7"
install:
  - pip install -r requirements.txt
  - npm install -g pa11y
script:
  - pytest
  - python setup.py install
  - adr-viewer
  - pa11y ./index.html --include-warnings --standard Section508 --level warning